languages:
  English:
    code: "en_US"
    is_default: true
  Português:
    code: "pt_BR"

models:
  Llama3:
    code: "llama3.2"
    is_default: true
  Gemma:
    code: "gemma2"
  Llama3-vision:
    code: "llama3.2-vision"
  ChatGPT:
    code: "gpt-4o"
  Qwen:
    code: "qwen2.5"